/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Company;

/**
 *
 * @author gigie
 */
public class DashboardHP extends javax.swing.JFrame {
    public static Company hp;
    public static Company apple;
    /**
     * Creates new form Dashboard
     */
    public DashboardHP(Company hp, Company apple) {
        this.hp = hp;
        this.apple = apple;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
   
    public void updateComputerCount(int count) {
        cE.setText(String.valueOf(count));
    }

    public void updateGraphicComputerCount(int count) {
        cG.setText(String.valueOf(count));
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NodeComputadoras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ePB = new javax.swing.JLabel();
        cG = new javax.swing.JLabel();
        eRAM = new javax.swing.JLabel();
        eFA = new javax.swing.JLabel();
        mE = new javax.swing.JLabel();
        aPB = new javax.swing.JLabel();
        aCPU = new javax.swing.JLabel();
        aRAM = new javax.swing.JLabel();
        NodeComputadoras1 = new javax.swing.JLabel();
        aTG = new javax.swing.JLabel();
        cE = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eTG = new javax.swing.JLabel();
        aFA = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        eCPU = new javax.swing.JLabel();
        HP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Trabajadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        NodeComputadoras.setText("Computador con tarjeta gráfica:");
        getContentPane().add(NodeComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 190, 20));

        jLabel2.setText("Placa Base");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("CPU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Memoria RAM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("Fuente de Alimentación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setText("HP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel7.setText("Almacén");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel9.setText("Máximo de trabajadores:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));

        ePB.setText("0");
        getContentPane().add(ePB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, -1));

        cG.setText("0");
        getContentPane().add(cG, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 50, -1));

        eRAM.setText("0");
        getContentPane().add(eRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, -1));

        eFA.setText("0");
        getContentPane().add(eFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 50, -1));

        mE.setText("0");
        getContentPane().add(mE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 50, -1));

        aPB.setText("0");
        getContentPane().add(aPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 50, -1));

        aCPU.setText("0");
        getContentPane().add(aCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, -1));

        aRAM.setText("0");
        getContentPane().add(aRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 50, -1));

        NodeComputadoras1.setText("Computador Estándar:");
        getContentPane().add(NodeComputadoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 120, 20));

        aTG.setText("0");
        getContentPane().add(aTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 50, -1));

        cE.setText("0");
        getContentPane().add(cE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 50, -1));

        jLabel20.setText("Director");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        eTG.setText("0");
        getContentPane().add(eTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 50, -1));

        aFA.setText("0");
        getContentPane().add(aFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 50, -1));

        jLabel23.setText("Tarjetas Gráficas");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel24.setText("Ensamblador");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel25.setText("Project Manager");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        eCPU.setText("0");
        getContentPane().add(eCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, -1));

        HP.setText("Ir a Apple");
        HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPActionPerformed(evt);
            }
        });
        getContentPane().add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPActionPerformed
      DashboardApple dApple = new DashboardApple(hp, apple);
      dApple.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_HPActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HP;
    private javax.swing.JLabel NodeComputadoras;
    private javax.swing.JLabel NodeComputadoras1;
    private javax.swing.JLabel aCPU;
    private javax.swing.JLabel aFA;
    private javax.swing.JLabel aPB;
    private javax.swing.JLabel aRAM;
    private javax.swing.JLabel aTG;
    private javax.swing.JLabel cE;
    private javax.swing.JLabel cG;
    private javax.swing.JLabel eCPU;
    private javax.swing.JLabel eFA;
    private javax.swing.JLabel ePB;
    private javax.swing.JLabel eRAM;
    private javax.swing.JLabel eTG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mE;
    // End of variables declaration//GEN-END:variables
}
