/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Company;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author gigie
 */
public class DashboardApple extends javax.swing.JFrame {
    public static Company hp;
    public static Company apple;
    /**
     * Creates new form Dashboard
     */
     
   
    
    public DashboardApple(Company hp, Company apple) {
        this.hp = hp;
        this.apple = apple;
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        showInfo();
    }
    
    public void showInfo() {
        this.apple.setWindowApple(this);
        this.apple.printApple();
    }
    
    public void updateComputerCount(int count) {
        cE.setText(String.valueOf(count));
        
    }

    public void updateGraphicComputerCount(int count) {
        cG.setText(String.valueOf(count));
    }
    
    public JLabel getEpb2() {
        return ePB2;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NodeComputadoras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ePB = new javax.swing.JLabel();
        cG = new javax.swing.JLabel();
        eRAM = new javax.swing.JLabel();
        eFA = new javax.swing.JLabel();
        mE = new javax.swing.JLabel();
        aPB = new javax.swing.JLabel();
        aCPU = new javax.swing.JLabel();
        aRAM = new javax.swing.JLabel();
        NodeComputadoras1 = new javax.swing.JLabel();
        aTG = new javax.swing.JLabel();
        cE = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eTG = new javax.swing.JLabel();
        aFA = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        eCPU = new javax.swing.JLabel();
        HP = new javax.swing.JButton();
        iFA = new javax.swing.JButton();
        iPB = new javax.swing.JButton();
        iRAM = new javax.swing.JButton();
        iE = new javax.swing.JButton();
        iCPU = new javax.swing.JButton();
        eTG1 = new javax.swing.JLabel();
        iTG = new javax.swing.JButton();
        dTG = new javax.swing.JButton();
        dPB = new javax.swing.JButton();
        dRAM = new javax.swing.JButton();
        dE = new javax.swing.JButton();
        dCPU = new javax.swing.JButton();
        aCPU1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ePB1 = new javax.swing.JLabel();
        ePB2 = new javax.swing.JLabel();
        ePB3 = new javax.swing.JLabel();
        mApple = new javax.swing.JLabel();
        mE2 = new javax.swing.JLabel();
        mE3 = new javax.swing.JLabel();
        mE4 = new javax.swing.JLabel();
        dFA1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Penalización");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        NodeComputadoras.setText("Computador con tarjeta gráfica:");
        jPanel1.add(NodeComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 190, 20));

        jLabel2.setText("Placa Base");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("CPU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("Memoria RAM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setText("Fuente de Alimentación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setText("Apple");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel7.setText("Costos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel9.setText("Máximo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 50, -1));

        ePB.setText("0");
        jPanel1.add(ePB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 20, -1));

        cG.setText("0");
        jPanel1.add(cG, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, -1));

        eRAM.setText("1");
        jPanel1.add(eRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 10, -1));

        eFA.setText("1");
        jPanel1.add(eFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 10, -1));

        mE.setText("0");
        jPanel1.add(mE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 80, -1));

        aPB.setText("0 / 0");
        jPanel1.add(aPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 50, 20));

        aCPU.setText("0 / 0");
        jPanel1.add(aCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 50, -1));

        aRAM.setText("0 / 0");
        jPanel1.add(aRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 50, -1));

        NodeComputadoras1.setText("Computador Estándar:");
        jPanel1.add(NodeComputadoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 20));

        aTG.setText("0 / 0");
        jPanel1.add(aTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 50, -1));

        cE.setText("0");
        jPanel1.add(cE, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 50, -1));

        jLabel20.setText("Director");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        eTG.setText("1");
        jPanel1.add(eTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 10, -1));

        aFA.setText("0 / 0 ");
        jPanel1.add(aFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 50, -1));

        jLabel23.setText("Tarjetas Gráficas");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel24.setText("Ensamblador");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel25.setText("Project Manager");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        eCPU.setText("1");
        jPanel1.add(eCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 10, -1));

        HP.setText("Ir a HP");
        HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPActionPerformed(evt);
            }
        });
        jPanel1.add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        iFA.setText("+");
        iFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iFAActionPerformed(evt);
            }
        });
        jPanel1.add(iFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        iPB.setText("+");
        iPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPBActionPerformed(evt);
            }
        });
        jPanel1.add(iPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        iRAM.setText("+");
        iRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iRAMActionPerformed(evt);
            }
        });
        jPanel1.add(iRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        iE.setText("+");
        iE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iEActionPerformed(evt);
            }
        });
        jPanel1.add(iE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        iCPU.setText("+");
        iCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCPUActionPerformed(evt);
            }
        });
        jPanel1.add(iCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        eTG1.setText("1");
        jPanel1.add(eTG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 10, -1));

        iTG.setText("+");
        iTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTGActionPerformed(evt);
            }
        });
        jPanel1.add(iTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        dTG.setText("-");
        dTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTGActionPerformed(evt);
            }
        });
        jPanel1.add(dTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        dPB.setText("-");
        dPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPBActionPerformed(evt);
            }
        });
        jPanel1.add(dPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        dRAM.setText("-");
        dRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRAMActionPerformed(evt);
            }
        });
        jPanel1.add(dRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        dE.setText("-");
        dE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dEActionPerformed(evt);
            }
        });
        jPanel1.add(dE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        dCPU.setText("-");
        dCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dCPUActionPerformed(evt);
            }
        });
        jPanel1.add(dCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        aCPU1.setText("0 / 0");
        jPanel1.add(aCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, -1));

        jLabel10.setText("Trabajadores");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel11.setText("Estado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel12.setText("Estado");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel13.setText("Faltas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel14.setText("Almacén");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel15.setText("Costos Operativos: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel16.setText("Ganancias");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel17.setText("Ganancia Neta: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel18.setText("Ganancia Bruta: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        ePB1.setText("1");
        jPanel1.add(ePB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 20, -1));

        ePB2.setText("0");
        jPanel1.add(ePB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        ePB3.setText("0");
        jPanel1.add(ePB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 60, -1));

        mApple.setText("0");
        jPanel1.add(mApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 20, -1));

        mE2.setText("\"estado\"");
        jPanel1.add(mE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 80, -1));

        mE3.setText("\"estado\"");
        jPanel1.add(mE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 80, -1));

        mE4.setText("0");
        jPanel1.add(mE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 30, 20));

        dFA1.setText("-");
        dFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dFA1ActionPerformed(evt);
            }
        });
        jPanel1.add(dFA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPActionPerformed
      DashboardHP dHP = new DashboardHP(hp, apple);
      dHP.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_HPActionPerformed

    private void iFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iFAActionPerformed

    private void iPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPBActionPerformed

    private void iRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iRAMActionPerformed

    private void iEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iEActionPerformed

    private void iCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCPUActionPerformed

    private void iTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iTGActionPerformed

    private void dTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTGActionPerformed

    private void dPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dPBActionPerformed

    private void dRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dRAMActionPerformed

    private void dEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dEActionPerformed

    private void dCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dCPUActionPerformed

    private void dFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dFA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dFA1ActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
  
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HP;
    private javax.swing.JLabel NodeComputadoras;
    private javax.swing.JLabel NodeComputadoras1;
    private javax.swing.JLabel aCPU;
    private javax.swing.JLabel aCPU1;
    private javax.swing.JLabel aFA;
    private javax.swing.JLabel aPB;
    private javax.swing.JLabel aRAM;
    private javax.swing.JLabel aTG;
    private javax.swing.JLabel cE;
    private javax.swing.JLabel cG;
    private javax.swing.JButton dCPU;
    private javax.swing.JButton dE;
    private javax.swing.JButton dFA1;
    private javax.swing.JButton dPB;
    private javax.swing.JButton dRAM;
    private javax.swing.JButton dTG;
    private javax.swing.JLabel eCPU;
    private javax.swing.JLabel eFA;
    private javax.swing.JLabel ePB;
    private javax.swing.JLabel ePB1;
    private javax.swing.JLabel ePB2;
    private javax.swing.JLabel ePB3;
    private javax.swing.JLabel eRAM;
    private javax.swing.JLabel eTG;
    private javax.swing.JLabel eTG1;
    private javax.swing.JButton iCPU;
    private javax.swing.JButton iE;
    private javax.swing.JButton iFA;
    private javax.swing.JButton iPB;
    private javax.swing.JButton iRAM;
    private javax.swing.JButton iTG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mApple;
    private javax.swing.JLabel mE;
    private javax.swing.JLabel mE2;
    private javax.swing.JLabel mE3;
    private javax.swing.JLabel mE4;
    // End of variables declaration//GEN-END:variables
}
