/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Company;
import DataStructure.Data;
import static Main.App.apple;
import static Main.App.hp;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author gigie
 */
public class Inicio extends javax.swing.JFrame {
    public static Company hp;
    public static Company apple;
    /**
     * Creates new form Inicio
     */
    public Inicio(Company c){
        if (c.getCompany() == "APPLE"){
            this.apple = c;
        } else {
            this.hp = c;
        
        }
    }
    
    
    public Inicio(Company hp, Company apple) {
        initComponents();
        loadFromFile();
        if (this.hp == null && this.apple == null) {
            hp = new Company("HP", 20, Data.daysLeft);
            apple = new Company("APPLE", 15, Data.daysLeft);
        }
        this.hp = hp;
        this.apple = apple;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void loadFromFile() {
        try {
            File file = new File("./src/Public/settings.txt");
            
//            if (!file.exists()) {
////                file.getParentFile().mkdirs(); // Crea los directorios necesarios si no existen
//                file.createNewFile(); // Crea el archivo si no existe
//                return;
//            }
            
            Scanner scanner = new Scanner(file);

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();

                // Separar el nombre del parámetro y el valor
                String[] parts = line.split(": ");
                String parameterName = parts[0];
                String parameterValue = parts[1];
                System.out.println(parameterName + parameterValue);

                // Asignar los valores a los JTextFields y variables correspondientes
                switch (parameterName) {
                    case "Duracion del dia (segundos)":
                        // Asignar al JTextField correspondiente y a la variable global
                    
                        Data.dayDuration = Integer.parseInt(parameterValue) * 1000; // Convertir a milisegundos
                        break;
                    case "Dias para entrega":
                        Data.totalDays = Integer.parseInt(parameterValue);
                        break;
//                    case "Trabajadores tipo Placa Base":
//                        PlacaBaseTextField.setText(parameterValue);
//                        Data.workerCounts[0] = Integer.parseInt(parameterValue);
//                        break;
//                    case "Trabajadores tipo CPU":
//                        CPUTextField.setText(parameterValue);
//                        Data.workerCounts[1] = Integer.parseInt(parameterValue);
//                        break;
//                    case "Trabajadores tipo RAM":
//                        RamMemoryTextField.setText(parameterValue);
//                        Data.workerCounts[2] = Integer.parseInt(parameterValue);
//                        break;
//                    case "Trabajadores tipo Fuente de Alimentacion":
//                        FuenteATextField.setText(parameterValue);
//                        Data.workerCounts[3] = Integer.parseInt(parameterValue);
//                        break;
//                    case "Ensambladores":
//                        AssemblersTextField.setText(parameterValue);
//                        Data.workerCounts[4] = Integer.parseInt(parameterValue);
//                        break;
                    default:
                        System.out.println("Parámetro desconocido: " + parameterName);
                        break;
                }
            }
            scanner.close();
            System.out.println("Parámetros cargados correctamente.");
        } catch (FileNotFoundException e) {
            System.out.println("Archivo no encontrado.");
            
            e.printStackTrace();
        } 
//        catch (IOException ex) {
//            Logger.getLogger(TxtDataApple.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HP = new javax.swing.JButton();
        AppleButton = new javax.swing.JButton();
        DataTxtAppleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HP.setText("Ir a HP");
        HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPActionPerformed(evt);
            }
        });
        jPanel1.add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 90, -1));

        AppleButton.setText("Ir a Apple");
        AppleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AppleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        DataTxtAppleButton.setText("Cambiar Data TXT");
        DataTxtAppleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTxtAppleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DataTxtAppleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 400, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPActionPerformed
        DashboardHP dHP = new DashboardHP(hp, apple);
        this.dispose();
    }//GEN-LAST:event_HPActionPerformed

    private void AppleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleButtonActionPerformed
       DashboardApple dApple = new DashboardApple(hp, apple);
       this.dispose();
       
    }//GEN-LAST:event_AppleButtonActionPerformed

    private void DataTxtAppleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTxtAppleButtonActionPerformed
        // TODO add your handling code here:
        TxtData txtDataApple = new TxtData(this);
        this.setVisible(false);
    }//GEN-LAST:event_DataTxtAppleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio(hp, apple).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppleButton;
    private javax.swing.JButton DataTxtAppleButton;
    private javax.swing.JButton HP;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
