/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Company;

/**
 *
 * @author gigie
 */
public class Inicio extends javax.swing.JFrame {
    public static Company hp;
    public static Company apple;
    /**
     * Creates new form Inicio
     */
    public Inicio(Company c){
        if (c.getCompany() == "APPLE"){
            this.apple = c;
        } else {
            this.hp = c;
        
        }
    }
    
    
    public Inicio(Company hp, Company apple) {
        this.hp = hp;
        this.apple = apple;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HP = new javax.swing.JButton();
        AppleButton = new javax.swing.JButton();
        DataTxtAppleButton = new javax.swing.JButton();
        DataTxtHPButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HP.setText("Ir a HP");
        HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPActionPerformed(evt);
            }
        });
        jPanel1.add(HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 90, -1));

        AppleButton.setText("Ir a Apple");
        AppleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AppleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        DataTxtAppleButton.setText("Cambiar Data Apple TXT");
        DataTxtAppleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTxtAppleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DataTxtAppleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        DataTxtHPButton.setText("Cambiar Data HP TXT");
        DataTxtHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTxtHPButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DataTxtHPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 400, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPActionPerformed
        DashboardHP dHP = new DashboardHP(hp, apple);
        this.dispose();
    }//GEN-LAST:event_HPActionPerformed

    private void AppleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleButtonActionPerformed
       DashboardApple dApple = new DashboardApple(hp, apple);
       this.dispose();
       
    }//GEN-LAST:event_AppleButtonActionPerformed

    private void DataTxtAppleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTxtAppleButtonActionPerformed
        // TODO add your handling code here:
        TxtDataApple txtDataApple = new TxtDataApple(this);
        this.setVisible(false);
    }//GEN-LAST:event_DataTxtAppleButtonActionPerformed

    private void DataTxtHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTxtHPButtonActionPerformed
        // TODO add your handling code here:
        TxtDataHP txtDataHP = new TxtDataHP(this);
        this.setVisible(false);
    }//GEN-LAST:event_DataTxtHPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio(hp, apple).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppleButton;
    private javax.swing.JButton DataTxtAppleButton;
    private javax.swing.JButton DataTxtHPButton;
    private javax.swing.JButton HP;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
